FROM python:3.12-alpine as base-app

ARG DEV=true

ENV PYTHONBUFFERED=1
ENV PYTHONFAULTHANDLER=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONHASHSEED=random
ENV PIP_NO_CACHE_DIR=off
ENV PIP_DISABLE_PIP_VERSION_CHECK=on
ENV PIP_DEFAULT_TIMEOUT=100
ENV POETRY_VERSION=1.8.2

FROM base-app as app-dependencies

WORKDIR /src

COPY ./pyproject.toml .
COPY ./poetry.lock .
COPY ./app ./app

COPY ./scripts ./scripts

RUN set -e

RUN pip install "poetry==$POETRY_VERSION" && \
    poetry config virtualenvs.create false && \
    if [ $DEV = "true" ]; then \
        poetry install --no-interaction --no-root --no-ansi ; \
    else \
        poetry install --no-interaction --no-root --no-ansi --no-dev ; \
    fi

FROM app-dependencies as app

CMD sh /src/scripts/run_app.sh
