up:
	docker compose up --force-recreate --remove-orphans

up-detached:
	docker compose up --force-recreate --remove-orphans --detach

help:
	@echo "Available commands:"
	@echo "  up            Start the Docker containers, force recreate them, and remove any orphans."
	@echo "  up-detach     Start the Docker containers in detached mode, force recreate them, and remove any orphans."

.PHONY: help up up-detach